name: Memo App CI/CD pipeline

on:
  push:
    branches:
      - 'development'        # My current dev env
      - 'staging'     
      - 'production' 
      - 'feature/**'
    paths:
      - 'app-module/**'  
  workflow_dispatch:  

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  app-deploy:
    # specify Runner details: Self-hosted or GitHub Runner
    environment: development
    runs-on: "ubuntu-24.04"

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: gha-terraform-session

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: memo-app-frontend-{{ vars.DEV  }}
          IMAGE_TAG: 0.1
        working-directory: ./app-module/frontend
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG   
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: memo-app-backend-${{ vars.DEV }}
          IMAGE_TAG: 0.1
        working-directory: ./app-module/backend
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG  

      - name: Login to AWS EKS
        run: aws eks update-kubeconfig --name EKS-Project-X

      - name: Deploy App to Kubernetes
        working-directory: ./api-backend
        run: |
          helm upgrade --install reviews-app-backend ./app-helm-chart/ \
            --values values/dev-values.yaml \
            --namespace reviews-app --create-namespace