# name: Terraform Deploy 

# on:
#   push:
#     branches:
#       - 'development'        # My current dev env
#       - 'staging'     
#       - 'production' 
#       - 'feature/**'
#     paths:
#       - 'infra-module/**'  
#   workflow_dispatch:  

# permissions:
#   id-token: write  
#   contents: read   

# jobs:
#   deploy:
#     environment: development  # Environment for this workflow
#     runs-on: ubuntu-22.04 

#     steps:
#       - name: Clone repo
#         uses: actions/checkout@v3

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-region: ${{ vars.REGION }}  
#           role-to-assume: ${{ vars.IAM_ROLE }}  
#           role-session-name: gha-terraform-session
          

#       - name: Deploy Terraform code
#         env:
#         working-directory: infra-module/
#         run: |
#           terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" 
#           terraform fmt 
#           terraform validate 
#           terraform plan -input=false -var-file=${{ vars.DEV }}.tfvars 
#           terraform destroy -auto-approve -input=false -var-file=${{ vars.DEV }}.tfvars 